import sys
import argparse
import re
import json
import os
from llama_cpp import Llama
from pydantic import BaseModel, Field
from typing import Optional

# Configuration - converting relative paths to absolute based on script location
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(SCRIPT_DIR, "model/llama3-gaja-hindi-8b-v0.1.Q4_K_M.gguf")
PROMPT_FILE = os.path.join(SCRIPT_DIR, "prompt.txt")
CONVERSATION_FILE = os.path.join(SCRIPT_DIR, "sample_conversation.txt")

class TravelAdvisory(BaseModel):
    destination: str = Field(..., description="The destination mentioned")
    is_safe: bool = Field(..., description="Whether it is safe to travel")
    sentiment: str = Field(..., description="Sentiment: POSITIVE or NEGATIVE")
    reason: Optional[str] = Field(None, description="Reason if unsafe")
    alternate_destination: Optional[str] = Field(None, description="Alternative destination if unsafe")
    warm_gesture: str = Field(..., description="A warm closing message based on safety")

def load_file(filepath):
    if not os.path.exists(filepath):
        # Fallback 
        return "" 
    with open(filepath, 'r', encoding='utf-8') as f:
        return f.read()

def main():
    parser = argparse.ArgumentParser(description='Analyze travel sentiment.')
    parser.add_argument('input_text', type=str, nargs='?', help='The text to analyze (optional)')
    args = parser.parse_args()

    # Determine functionality mode
    # If input_text is provided, we are in API MODE (CLI argument, JSON only)
    # If not, we are in LEGACY MODE (read file, print human readable)
    is_api_mode = args.input_text is not None

    if is_api_mode:
        # Redirect stderr to suppress Llama logs
        sys.stderr = open(os.devnull, 'w')

    if not os.path.exists(MODEL_PATH):
        error_msg = {"error": f"Model not found at {MODEL_PATH}"}
        if is_api_mode:
            print(json.dumps(error_msg))
        else:
            print(error_msg['error'])
        return

    try:
        llm = Llama(
            model_path=MODEL_PATH,
            n_ctx=2048,
            n_gpu_layers=-1, 
            verbose=False
        )
    except Exception as e:
        if is_api_mode:
             sys.stderr = sys.__stderr__ 
             print(json.dumps({"error": f"Failed to load model: {str(e)}"}))
        else:
             print(f"Error loading model: {e}")
        return

    if is_api_mode:
        sys.stderr = sys.__stderr__ # Restore stderr
        conversation_content = f"User: {args.input_text}"
    else:
        print("Loading model...")
        conversation_content = load_file(CONVERSATION_FILE)
        print("Analyzing conversation...")

    # Load prompt template
    prompt_template = load_file(PROMPT_FILE)
    
    # Format prompt
    full_prompt = prompt_template.format(conversation=conversation_content)

    # Generate response
    output = llm(
        full_prompt,
        max_tokens=600,
        echo=False,
        temperature=0.5
    )

    # Extract text content
    response_text = output['choices'][0]['text'].strip()
    
    # Regex extraction of JSON
    json_matches = re.findall(r'\{.*?\}', response_text, re.DOTALL)
    
    valid_json_found = False
    result_json = {"error": "No valid JSON generated by model"}

    for match in json_matches:
        try:
            # Fix common Python vs JSON mismatches
            clean_match = match.replace("True", "true").replace("False", "false").replace("None", "null")
            parsed = json.loads(clean_match)
            if "is_safe" in parsed:
                result_json = parsed
                valid_json_found = True
                break 
        except:
            continue
            
    if is_api_mode:
        # API Output: Pure JSON
        print(json.dumps(result_json, indent=2))
    else:
        # Legacy Output: Human Readable
        if not valid_json_found:
             print("Warning: No valid JSON block found in output.")
        
        print("\n--- JSON Result ---")
        print(json.dumps(result_json, indent=2) if valid_json_found else response_text)
        print("-------------------\n")

        if valid_json_found:
            try:
                advisory = TravelAdvisory(**result_json)
                print("Successfully validated advisory.")
                print(f"Warm Gesture: {advisory.warm_gesture}")
            except Exception as e:
                print(f"Validation Error: {e}")

if __name__ == "__main__":
    main()
